name: lint
on:
  push: {}
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Python 3.12 Lint
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade tox tox-gh-actions
    - name: Verify installation
      run: |
        python --version
        python -m pip --version
        python -m pip show setuptools wheel tox tox-gh-actions
    - name: Run Lint
      run: tox -e lint
